apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: wazuh  # 👈 Add this line
 
resources:
- manager_serviceaccount.yaml
- ../../wazuh
 
patches:
- path: storage-class.yaml
- path: indexer-resources.yaml
- path: dashboard-resources.yaml
- path: wazuh-master-resources.yaml
- path: wazuh-worker-resources.yaml
 
