apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Required by Wazuh dashboard config
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: NodePort
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
      nodePort: 31515  # optional, must be within 30000-32767 range
    - name: api
      port: 55000
      targetPort: 55000
      nodePort: 32500  # optional

