apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""     # empty = no StorageClass
  awsElasticBlockStore:
    volumeID: "vol-06081766af0cf83c1"
    fsType: "ext4"

