apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        env:
         - name: GF_SMTP_ENABLED
           value: "true"
         - name: GF_SMTP_HOST
           value: "smtp.gmail.com:587"
         - name: GF_SMTP_USER
           value: "piyush211997@gmail.com"
         - name: GF_SMTP_PASSWORD
           valueFrom:
             secretKeyRef:
               name: grafana-smtp-secret
               key: SMTP_PASSWORD
         - name: GF_SMTP_FROM_ADDRESS
           value: "donbhai@gmail.com"
         - name: GF_SMTP_FROM_NAME
           value: "Grafana"
         - name: GF_SMTP_SKIP_VERIFY
           value: "true"
         - name: GF_SERVER_ROOT_URL
           value: "http://a310aa2dbf6dd403d823f15e3c24ab58-768467364.ap-south-1.elb.amazonaws.com:3000"
         - name: GF_SERVER_DOMAIN
           value: "a310aa2dbf6dd403d823f15e3c24ab58-768467364.ap-south-1.elb.amazonaws.com"
  
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests: 
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
              claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
