apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterrole.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-smtp-secret.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml

